/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";

export interface AsEuint8TestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "castFromEboolToEuint8"
      | "castFromEuint16ToEuint8"
      | "castFromEuint32ToEuint8"
      | "castFromPlaintextToEuint8"
      | "castFromPreEncryptedToEuint8"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "castFromEboolToEuint8",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromEuint16ToEuint8",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromEuint32ToEuint8",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromPlaintextToEuint8",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromPreEncryptedToEuint8",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "castFromEboolToEuint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromEuint16ToEuint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromEuint32ToEuint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromPlaintextToEuint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromPreEncryptedToEuint8",
    data: BytesLike
  ): Result;
}

export interface AsEuint8Test extends BaseContract {
  connect(runner?: ContractRunner | null): AsEuint8Test;
  waitForDeployment(): Promise<this>;

  interface: AsEuint8TestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  castFromEboolToEuint8: TypedContractMethod<
    [val: BigNumberish],
    [bigint],
    "view"
  >;

  castFromEuint16ToEuint8: TypedContractMethod<
    [val: BigNumberish],
    [bigint],
    "view"
  >;

  castFromEuint32ToEuint8: TypedContractMethod<
    [val: BigNumberish],
    [bigint],
    "view"
  >;

  castFromPlaintextToEuint8: TypedContractMethod<
    [val: BigNumberish],
    [bigint],
    "view"
  >;

  castFromPreEncryptedToEuint8: TypedContractMethod<
    [val: BytesLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "castFromEboolToEuint8"
  ): TypedContractMethod<[val: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromEuint16ToEuint8"
  ): TypedContractMethod<[val: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromEuint32ToEuint8"
  ): TypedContractMethod<[val: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromPlaintextToEuint8"
  ): TypedContractMethod<[val: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromPreEncryptedToEuint8"
  ): TypedContractMethod<[val: BytesLike], [bigint], "view">;

  filters: {};
}
