/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface AsEuint16TestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "castFromEboolToEuint16"
      | "castFromEuint32ToEuint16"
      | "castFromEuint8ToEuint16"
      | "castFromPlaintextToEuint16"
      | "castFromPreEncryptedToEuint16"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "castFromEboolToEuint16",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromEuint32ToEuint16",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromEuint8ToEuint16",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromPlaintextToEuint16",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromPreEncryptedToEuint16",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "castFromEboolToEuint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromEuint32ToEuint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromEuint8ToEuint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromPlaintextToEuint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromPreEncryptedToEuint16",
    data: BytesLike
  ): Result;
}

export interface AsEuint16Test extends BaseContract {
  connect(runner?: ContractRunner | null): AsEuint16Test;
  waitForDeployment(): Promise<this>;

  interface: AsEuint16TestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  castFromEboolToEuint16: TypedContractMethod<
    [val: BigNumberish, test: string],
    [bigint],
    "view"
  >;

  castFromEuint32ToEuint16: TypedContractMethod<
    [val: BigNumberish, test: string],
    [bigint],
    "view"
  >;

  castFromEuint8ToEuint16: TypedContractMethod<
    [val: BigNumberish, test: string],
    [bigint],
    "view"
  >;

  castFromPlaintextToEuint16: TypedContractMethod<
    [val: BigNumberish],
    [bigint],
    "view"
  >;

  castFromPreEncryptedToEuint16: TypedContractMethod<
    [val: BytesLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "castFromEboolToEuint16"
  ): TypedContractMethod<[val: BigNumberish, test: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromEuint32ToEuint16"
  ): TypedContractMethod<[val: BigNumberish, test: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromEuint8ToEuint16"
  ): TypedContractMethod<[val: BigNumberish, test: string], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromPlaintextToEuint16"
  ): TypedContractMethod<[val: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromPreEncryptedToEuint16"
  ): TypedContractMethod<[val: BytesLike], [bigint], "view">;

  filters: {};
}
