/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";

export interface AsEuint32TestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "castFromEboolToEuint32"
      | "castFromEuint16ToEuint32"
      | "castFromEuint8ToEuint32"
      | "castFromPlaintextToEuint32"
      | "castFromPreEncryptedToEuint32"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "castFromEboolToEuint32",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromEuint16ToEuint32",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromEuint8ToEuint32",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromPlaintextToEuint32",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "castFromPreEncryptedToEuint32",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "castFromEboolToEuint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromEuint16ToEuint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromEuint8ToEuint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromPlaintextToEuint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castFromPreEncryptedToEuint32",
    data: BytesLike
  ): Result;
}

export interface AsEuint32Test extends BaseContract {
  connect(runner?: ContractRunner | null): AsEuint32Test;
  waitForDeployment(): Promise<this>;

  interface: AsEuint32TestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  castFromEboolToEuint32: TypedContractMethod<
    [val: BigNumberish],
    [bigint],
    "view"
  >;

  castFromEuint16ToEuint32: TypedContractMethod<
    [val: BigNumberish],
    [bigint],
    "view"
  >;

  castFromEuint8ToEuint32: TypedContractMethod<
    [val: BigNumberish],
    [bigint],
    "view"
  >;

  castFromPlaintextToEuint32: TypedContractMethod<
    [val: BigNumberish],
    [bigint],
    "view"
  >;

  castFromPreEncryptedToEuint32: TypedContractMethod<
    [val: BytesLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "castFromEboolToEuint32"
  ): TypedContractMethod<[val: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromEuint16ToEuint32"
  ): TypedContractMethod<[val: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromEuint8ToEuint32"
  ): TypedContractMethod<[val: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromPlaintextToEuint32"
  ): TypedContractMethod<[val: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "castFromPreEncryptedToEuint32"
  ): TypedContractMethod<[val: BytesLike], [bigint], "view">;

  filters: {};
}
