/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BindingsEboolInterface extends Interface {
  getFunction(
    nameOrSignature: "and" | "eq" | "ne" | "or" | "xor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "and",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eq",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ne",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "or",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "xor",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "and", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ne", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "or", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xor", data: BytesLike): Result;
}

export interface BindingsEbool extends BaseContract {
  connect(runner?: ContractRunner | null): BindingsEbool;
  waitForDeployment(): Promise<this>;

  interface: BindingsEboolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  and: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  eq: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  ne: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  or: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  xor: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "and"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "eq"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "ne"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "or"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "xor"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  filters: {};
}
