/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface BindingsEuint8Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "and"
      | "div"
      | "eq"
      | "gt"
      | "gte"
      | "lt"
      | "lte"
      | "max"
      | "min"
      | "mul"
      | "ne"
      | "or"
      | "rem"
      | "shl"
      | "shr"
      | "sub"
      | "xor"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "add",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "and",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "div",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eq",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gt",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "gte",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lt",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lte",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "max",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "min",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mul",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ne",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "or",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rem",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shl",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "shr",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sub",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "xor",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "and", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "div", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gte", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lte", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "max", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "min", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ne", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "or", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xor", data: BytesLike): Result;
}

export interface BindingsEuint8 extends BaseContract {
  connect(runner?: ContractRunner | null): BindingsEuint8;
  waitForDeployment(): Promise<this>;

  interface: BindingsEuint8Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  and: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  div: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  eq: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  gt: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  gte: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  lt: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  lte: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  max: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  min: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  mul: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  ne: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  or: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  rem: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  shl: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  shr: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  sub: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  xor: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "and"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "div"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "eq"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "gt"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "gte"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lt"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "lte"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "max"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "min"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "mul"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "ne"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "or"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "rem"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "shl"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "shr"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "sub"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "xor"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish],
    [bigint],
    "view"
  >;

  filters: {};
}
