// This file is auto-generated by solgen/templates/testContracts.ts
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import {FHE, euint8, euint16, euint32, euint64, euint128, euint256, ebool} from "../../FHE.sol";
import {Utils} from "./utils/Utils.sol";

error TestNotFound(string test);

contract RorTest {
    using Utils for *;
    
    function ror(string calldata test, uint256 a, uint256 b) public pure returns (uint256 output) {
        if (Utils.cmp(test, "ror(euint8,euint8)")) {
            return FHE.decrypt(FHE.ror(FHE.asEuint8(a), FHE.asEuint8(b)));
        } else if (Utils.cmp(test, "ror(euint16,euint16)")) {
            return FHE.decrypt(FHE.ror(FHE.asEuint16(a), FHE.asEuint16(b)));
        } else if (Utils.cmp(test, "ror(euint32,euint32)")) {
            return FHE.decrypt(FHE.ror(FHE.asEuint32(a), FHE.asEuint32(b)));
        } else if (Utils.cmp(test, "ror(euint64,euint64)")) {
            return FHE.decrypt(FHE.ror(FHE.asEuint64(a), FHE.asEuint64(b)));
        } else if (Utils.cmp(test, "ror(euint128,euint128)")) {
            return FHE.decrypt(FHE.ror(FHE.asEuint128(a), FHE.asEuint128(b)));
        } else if (Utils.cmp(test, "euint8.ror(euint8)")) {
            return FHE.decrypt(FHE.asEuint8(a).ror(FHE.asEuint8(b)));
        } else if (Utils.cmp(test, "euint16.ror(euint16)")) {
            return FHE.decrypt(FHE.asEuint16(a).ror(FHE.asEuint16(b)));
        } else if (Utils.cmp(test, "euint32.ror(euint32)")) {
            return FHE.decrypt(FHE.asEuint32(a).ror(FHE.asEuint32(b)));
        } else if (Utils.cmp(test, "euint64.ror(euint64)")) {
            return FHE.decrypt(FHE.asEuint64(a).ror(FHE.asEuint64(b)));
        } else if (Utils.cmp(test, "euint128.ror(euint128)")) {
            return FHE.decrypt(FHE.asEuint128(a).ror(FHE.asEuint128(b)));
        }
    
        revert TestNotFound(test);
    }
}
