/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";

export interface FheOpsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "add"
      | "and"
      | "cast"
      | "cmux"
      | "decrypt"
      | "div"
      | "eq"
      | "gt"
      | "gte"
      | "lt"
      | "lte"
      | "max"
      | "min"
      | "mul"
      | "ne"
      | "not"
      | "or"
      | "reencrypt"
      | "rem"
      | "req"
      | "shl"
      | "shr"
      | "sub"
      | "trivialEncrypt"
      | "verify"
      | "xor"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "add", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "and", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "cast", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "cmux", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "decrypt", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "div", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "eq", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "gt", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "gte", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "lt", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "lte", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "max", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "min", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "mul", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "ne", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "not", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "or", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "reencrypt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "rem", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "req", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "shl", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "shr", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "sub", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "trivialEncrypt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "verify", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "xor", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "and", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cast", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cmux", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decrypt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "div", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "eq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "gte", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lte", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "max", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "min", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ne", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "not", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "or", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "reencrypt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "req", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "shr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "trivialEncrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xor", data: BytesLike): Result;
}

export interface FheOps extends BaseContract {
  connect(runner?: ContractRunner | null): FheOps;
  waitForDeployment(): Promise<this>;

  interface: FheOpsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  add: TypedContractMethod<[input: BytesLike], [string], "view">;

  and: TypedContractMethod<[input: BytesLike], [string], "view">;

  cast: TypedContractMethod<[input: BytesLike], [string], "view">;

  cmux: TypedContractMethod<[input: BytesLike], [string], "view">;

  decrypt: TypedContractMethod<[input: BytesLike], [bigint], "view">;

  div: TypedContractMethod<[input: BytesLike], [string], "view">;

  eq: TypedContractMethod<[input: BytesLike], [string], "view">;

  gt: TypedContractMethod<[input: BytesLike], [string], "view">;

  gte: TypedContractMethod<[input: BytesLike], [string], "view">;

  lt: TypedContractMethod<[input: BytesLike], [string], "view">;

  lte: TypedContractMethod<[input: BytesLike], [string], "view">;

  max: TypedContractMethod<[input: BytesLike], [string], "view">;

  min: TypedContractMethod<[input: BytesLike], [string], "view">;

  mul: TypedContractMethod<[input: BytesLike], [string], "view">;

  ne: TypedContractMethod<[input: BytesLike], [string], "view">;

  not: TypedContractMethod<[input: BytesLike], [string], "view">;

  or: TypedContractMethod<[input: BytesLike], [string], "view">;

  reencrypt: TypedContractMethod<[input: BytesLike], [string], "view">;

  rem: TypedContractMethod<[input: BytesLike], [string], "view">;

  req: TypedContractMethod<[input: BytesLike], [string], "view">;

  shl: TypedContractMethod<[input: BytesLike], [string], "view">;

  shr: TypedContractMethod<[input: BytesLike], [string], "view">;

  sub: TypedContractMethod<[input: BytesLike], [string], "view">;

  trivialEncrypt: TypedContractMethod<[input: BytesLike], [string], "view">;

  verify: TypedContractMethod<[input: BytesLike], [string], "view">;

  xor: TypedContractMethod<[input: BytesLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "add"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "and"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "cast"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "cmux"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "decrypt"
  ): TypedContractMethod<[input: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "div"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "eq"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "gt"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "gte"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "lt"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "lte"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "max"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "min"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "mul"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "ne"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "not"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "or"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "reencrypt"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "rem"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "req"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "shl"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "shr"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "sub"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "trivialEncrypt"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "xor"
  ): TypedContractMethod<[input: BytesLike], [string], "view">;

  filters: {};
}
