name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      registry:
        required: true
        type: string
        default: "ghcr.io"
      image_name:
        required: true
        type: string
        default: "fhenixprotocol/cofhe/fheos"
      platforms:
        required: false
        type: string
        default: '["linux/amd64", "linux/arm64"]'
  release:
    types: [created]
  pull_request:
    paths:
      - '.github/workflows/image_build.yml'

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: FhenixProtocol/actions/.github/workflows/docker_build.yml@master
    with:
      registry: ${{ inputs.registry || 'ghcr.io' }}
      image_name: ${{ inputs.image_name || 'fhenixprotocol/actions-testing' }}
      platforms: ${{ inputs.platforms || '["linux/amd64", "linux/arm64"]' }}
    secrets:
      GCR_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
