name: Build and Deploy Docker Image

on:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: FhenixProtocol/Cofhe/fheos

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT_LIOR }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_LIOR }}

      - name: Extract metadata (tags, labels) for Coprocessor Docker image
        id: meta-coprocessor
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/coprocessor
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Extract metadata (tags, labels) for Engine Docker image
        id: meta-engine
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/engine
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Coprocessor Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: coprocessor.Dockerfile
          push: true
          tags: ${{ steps.meta-coprocessor.outputs.tags }}
          labels: ${{ steps.meta-coprocessor.outputs.labels }}

      - name: Build and push Engine Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: engine.Dockerfile
          push: true
          tags: ${{ steps.meta-engine.outputs.tags }}
          labels: ${{ steps.meta-engine.outputs.labels }}